---
- name: Collect facts
  become: true
  ansible.builtin.setup:

- name: Set values to dnf.conf
  become: true
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: "{{ item.section | default(omit) }}"
    option: "{{ item.option | default(omit) }}"
    values: "{{ item.values | default(omit) }}"
  loop: "{{ dnf_ini_values }}"
  when:
    - ansible_pkg_mgr == "dnf"
