---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: rocky8
    image: rockylinux:8
  - name: rocky9
    image: rockylinux:9
provisioner:
  name: ansible
verifier:
  name: ansible
